import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const comfortaa = Comfortaa({
	variable: "--font-comfortaa",
	subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={` ${comfortaa.variable} antialiased relative font-`}>
				<Navbar />

				{children}
			</body>
		</html>
	);
}
